version: "3.9"

services:
  backend:
    image: shravanvm/devops-assignment-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False

  frontend:
    image: shravanvm/devops-assignment-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend


