services:
  backend:
    image: shravanvm/devops-backend:latest
    container_name: backend
    restart: always
    environment:
      # Adjust these to match your backend (examples)
      DEBUG: "0"
      ALLOWED_HOSTS: "*"
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - appnet

  frontend:
    image: shravanvm/devops-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
